# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_multiview.ui'
#
# Created: Tue Mar  8 16:31:45 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MultiView(object):
    def setupUi(self, MultiView):
        MultiView.setObjectName("MultiView")
        MultiView.setWindowModality(QtCore.Qt.NonModal)
        MultiView.resize(803, 374)
        self.layoutWidget = QtGui.QWidget(MultiView)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left = QtGui.QVBoxLayout()
        self.left.setObjectName("left")
        self.title = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setObjectName("title")
        self.left.addWidget(self.title)
        self.scrollArea = QtGui.QScrollArea(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 388, 95))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.availableVariables = QtGui.QVBoxLayout()
        self.availableVariables.setObjectName("availableVariables")
        self.verticalLayout_5.addLayout(self.availableVariables)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.left.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.availableVariablesUpdateButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.availableVariablesUpdateButton.sizePolicy().hasHeightForWidth())
        self.availableVariablesUpdateButton.setSizePolicy(sizePolicy)
        self.availableVariablesUpdateButton.setObjectName("availableVariablesUpdateButton")
        self.horizontalLayout_2.addWidget(self.availableVariablesUpdateButton)
        self.loadDataButton = QtGui.QPushButton(self.layoutWidget)
        self.loadDataButton.setObjectName("loadDataButton")
        self.horizontalLayout_2.addWidget(self.loadDataButton)
        self.left.addLayout(self.horizontalLayout_2)
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 301, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.trackRightClick = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.trackRightClick.setObjectName("trackRightClick")
        self.horizontalLayout_5.addWidget(self.trackRightClick)
        self.trackMouseMove = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.trackMouseMove.setObjectName("trackMouseMove")
        self.horizontalLayout_5.addWidget(self.trackMouseMove)
        self.left.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.left)
        self.display = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display.sizePolicy().hasHeightForWidth())
        self.display.setSizePolicy(sizePolicy)
        self.display.setObjectName("display")
        self.horizontalLayout.addWidget(self.display)
        self.closeButton = QtGui.QPushButton(MultiView)
        self.closeButton.setGeometry(QtCore.QRect(600, 340, 191, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setObjectName("closeButton")

        self.retranslateUi(MultiView)
        QtCore.QMetaObject.connectSlotsByName(MultiView)

    def retranslateUi(self, MultiView):
        MultiView.setWindowTitle(QtGui.QApplication.translate("MultiView", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setText(QtGui.QApplication.translate("MultiView", "Enable Variables:", None, QtGui.QApplication.UnicodeUTF8))
        self.availableVariablesUpdateButton.setText(QtGui.QApplication.translate("MultiView", "Update List", None, QtGui.QApplication.UnicodeUTF8))
        self.loadDataButton.setText(QtGui.QApplication.translate("MultiView", "Load Data ...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MultiView", "Tracking:", None, QtGui.QApplication.UnicodeUTF8))
        self.trackRightClick.setText(QtGui.QApplication.translate("MultiView", "Right click", None, QtGui.QApplication.UnicodeUTF8))
        self.trackMouseMove.setText(QtGui.QApplication.translate("MultiView", "Mouse Move", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("MultiView", "Close", None, QtGui.QApplication.UnicodeUTF8))

