# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_multiview.ui'
#
# Created: Fri Mar 30 19:02:42 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MultiView(object):
    def setupUi(self, MultiView):
        MultiView.setObjectName(_fromUtf8("MultiView"))
        MultiView.setWindowModality(QtCore.Qt.NonModal)
        MultiView.resize(857, 488)
        MultiView.setWindowTitle(QtGui.QApplication.translate("MultiView", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_2 = QtGui.QVBoxLayout(MultiView)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.main = QtGui.QHBoxLayout()
        self.main.setObjectName(_fromUtf8("main"))
        self.controls = QtGui.QVBoxLayout()
        self.controls.setObjectName(_fromUtf8("controls"))
        self.title = QtGui.QLabel(MultiView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setText(QtGui.QApplication.translate("MultiView", "Enable Variables:", None, QtGui.QApplication.UnicodeUTF8))
        self.title.setObjectName(_fromUtf8("title"))
        self.controls.addWidget(self.title)
        self.availableVariablesContainer = QtGui.QScrollArea(MultiView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.availableVariablesContainer.sizePolicy().hasHeightForWidth())
        self.availableVariablesContainer.setSizePolicy(sizePolicy)
        self.availableVariablesContainer.setWidgetResizable(True)
        self.availableVariablesContainer.setObjectName(_fromUtf8("availableVariablesContainer"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 251, 191))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.availableVariables = QtGui.QVBoxLayout()
        self.availableVariables.setObjectName(_fromUtf8("availableVariables"))
        self.verticalLayout_5.addLayout(self.availableVariables)
        self.availableVariablesContainer.setWidget(self.scrollAreaWidgetContents_2)
        self.controls.addWidget(self.availableVariablesContainer)
        self.settings = QtGui.QHBoxLayout()
        self.settings.setObjectName(_fromUtf8("settings"))
        self.tracking = QtGui.QGroupBox(MultiView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tracking.sizePolicy().hasHeightForWidth())
        self.tracking.setSizePolicy(sizePolicy)
        self.tracking.setTitle(QtGui.QApplication.translate("MultiView", "Tracking:", None, QtGui.QApplication.UnicodeUTF8))
        self.tracking.setObjectName(_fromUtf8("tracking"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tracking)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.trackMouseMove = QtGui.QRadioButton(self.tracking)
        self.trackMouseMove.setText(QtGui.QApplication.translate("MultiView", "Mouse Move", None, QtGui.QApplication.UnicodeUTF8))
        self.trackMouseMove.setObjectName(_fromUtf8("trackMouseMove"))
        self.verticalLayout_3.addWidget(self.trackMouseMove)
        self.trackRightClick = QtGui.QRadioButton(self.tracking)
        self.trackRightClick.setText(QtGui.QApplication.translate("MultiView", "Right click", None, QtGui.QApplication.UnicodeUTF8))
        self.trackRightClick.setObjectName(_fromUtf8("trackRightClick"))
        self.verticalLayout_3.addWidget(self.trackRightClick)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.settings.addWidget(self.tracking)
        self.buttons = QtGui.QVBoxLayout()
        self.buttons.setObjectName(_fromUtf8("buttons"))
        self.manualRefreshButton = QtGui.QPushButton(MultiView)
        self.manualRefreshButton.setText(QtGui.QApplication.translate("MultiView", "Refresh List", None, QtGui.QApplication.UnicodeUTF8))
        self.manualRefreshButton.setObjectName(_fromUtf8("manualRefreshButton"))
        self.buttons.addWidget(self.manualRefreshButton)
        self.loadDataButton = QtGui.QPushButton(MultiView)
        self.loadDataButton.setText(QtGui.QApplication.translate("MultiView", "Load Data ...", None, QtGui.QApplication.UnicodeUTF8))
        self.loadDataButton.setObjectName(_fromUtf8("loadDataButton"))
        self.buttons.addWidget(self.loadDataButton)
        self.helpButton = QtGui.QPushButton(MultiView)
        self.helpButton.setText(QtGui.QApplication.translate("MultiView", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.helpButton.setObjectName(_fromUtf8("helpButton"))
        self.buttons.addWidget(self.helpButton)
        self.vizHelpButton = QtGui.QPushButton(MultiView)
        self.vizHelpButton.setText(QtGui.QApplication.translate("MultiView", "Viz Help", None, QtGui.QApplication.UnicodeUTF8))
        self.vizHelpButton.setObjectName(_fromUtf8("vizHelpButton"))
        self.buttons.addWidget(self.vizHelpButton)
        self.printButton = QtGui.QPushButton(MultiView)
        self.printButton.setText(QtGui.QApplication.translate("MultiView", "Print Viz", None, QtGui.QApplication.UnicodeUTF8))
        self.printButton.setObjectName(_fromUtf8("printButton"))
        self.buttons.addWidget(self.printButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.buttons.addItem(spacerItem1)
        self.settings.addLayout(self.buttons)
        self.controls.addLayout(self.settings)
        self.main.addLayout(self.controls)
        self.visualizations = QtGui.QTabWidget(MultiView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visualizations.sizePolicy().hasHeightForWidth())
        self.visualizations.setSizePolicy(sizePolicy)
        self.visualizations.setObjectName(_fromUtf8("visualizations"))
        self.main.addWidget(self.visualizations)
        self.verticalLayout_2.addLayout(self.main)
        self.bottom = QtGui.QHBoxLayout()
        self.bottom.setObjectName(_fromUtf8("bottom"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.bottom.addItem(spacerItem2)
        self.aboutButton = QtGui.QPushButton(MultiView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutButton.sizePolicy().hasHeightForWidth())
        self.aboutButton.setSizePolicy(sizePolicy)
        self.aboutButton.setText(QtGui.QApplication.translate("MultiView", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutButton.setObjectName(_fromUtf8("aboutButton"))
        self.bottom.addWidget(self.aboutButton)
        self.closeButton = QtGui.QPushButton(MultiView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setText(QtGui.QApplication.translate("MultiView", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.bottom.addWidget(self.closeButton)
        self.verticalLayout_2.addLayout(self.bottom)

        self.retranslateUi(MultiView)
        self.visualizations.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MultiView)

    def retranslateUi(self, MultiView):
        pass

